### ISSUE TITLE
Example doesn't work 

### ISSUE THREAD

**Issue by jenyckee** [collective-soundworks/soundworks-drops#1]
Example doesn't work with node v4.4.3 and Chrome Version 50.0.2661.102 (64-bit)

**Comment by b-ma** [comment]
Hi, 

Could you be more specific about your problem because the application actually does work. 
Do you get any errors or get stuck at some point of the application lifecycle ?

**Comment by jenyckee** [comment]
I get up to the point where it says syncing. After it the app is idle but doesn't do anything when tapping the screen.

**Comment by b-ma** [comment]
Are you locked on a page saying "Waiting for everybody getting ready…" ?
If so, you have to open a conductor (url: `http://your.ip:8000/conductor`) and actually start the performance. 
Tell me if it this works for you

**Comment by jenyckee** [comment]
Yes I opened a conductor but still don't hear any sounds.

it's also missing the /css/main.css?0.0.1 file.

**Comment by b-ma** [comment]
Hi,

I reinstalled everything for the third time using node 4.3.3, and everything still looks fine on my side... So if you could be a bit less laconic in your problem description, I could maybe try to help you.

Firstly, your css problem looks very strange, we had a bug untill last week but it should be fixed now, the version where this bug is fixed is the `v1.1.0` so maybe you could check in the `package.json` if you have the lastest release.

Then, can you start a fresh project and execute the following command:

```
git clone https://github.com/collective-soundworks/soundworks-drops.git your-folder
cd your-folder
npm install
npm run transpile
npm run start
```

Do you have any errors messages up to this point ?
Especially with the `transpile` command, is everything written in green, or do you have some lines in red ?(maybe you could just copy and paste the output of this command here, if anything looks weird)

If everything seems ok up to this point, from the clients perspective, do you have any errors in the console (for both the `/` and `conductor` route) ?

Finally, could you give the your `npm` version, and what operating system are you running ?

Thanks

**Comment by jenyckee** [comment]
```
~/sandbox/soundworks-drops masterλ npm run transpile

> drops@1.0.1 transpile /Users/jenyckee/sandbox/soundworks-drops
> node ./bin/runner --transpile

[drops] src/server/PlayerExperience.js: successfully transpiled to "server/PlayerExperience.js" (4004ms)
[drops] sass/_02-commons.scss (180:3): sass error
> Base-level rules cannot contain the parent-selector-referencing character '&'.

Backtrace:
    sass/_02-commons.scss:180
[drops] src/server/index.js: successfully transpiled to "server/index.js" (70ms)
[drops] src/client/conductor/index.js: successfully transpiled to "client/conductor/index.js" (21ms)
[drops] src/client/player/Circles.js: successfully transpiled to "client/player/Circles.js" (87ms)
[drops] src/client/player/Looper.js: successfully transpiled to "client/player/Looper.js" (107ms)
[drops] src/client/player/PlayerExperience.js: successfully transpiled to "client/player/PlayerExperience.js" (143ms)
[drops] src/client/player/SampleSynth.js: successfully transpiled to "client/player/SampleSynth.js" (59ms)
[drops] src/client/player/audioFiles.js: successfully transpiled to "client/player/audioFiles.js" (7ms)
[drops] src/client/player/index.js: successfully transpiled to "client/player/index.js" (12ms)
[drops] public/js/conductor.js: successfully created (5477ms)
[drops] public/js/player.js: successfully created (5474ms)
~/sandbox/soundworks-drops masterλ npm -v
3.8.6
```

Sorry if my description was not very clear. I quickly reran the commands and this is my output. I'll have a deeper look into it tonight and come back to you. Thanks for your help anyways

**Comment by b-ma** [comment]
Ok thanks, 
it looks like you don't have the lastest version of the project because you have this bug in the sass files, which is fixed now:

```
[drops] sass/_02-commons.scss (180:3): sass error
> Base-level rules cannot contain the parent-selector-referencing character '&'.

Backtrace:
    sass/_02-commons.scss:180
```

So the first thing to do anyway is to restart a fresh project from the lastest version, and we will see if it fixes your problem

**Comment by jenyckee** [comment]
Ok all is fine now. I had indeed an outdated version of the project. Didn't clone it too long ago though. Thanks anyway!
